name: Sandbox Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SANDBOX_NAMESPACE: sandbox
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  YC_SA_KEY_JSON: ${{ secrets.YC_SA_KEY_JSON }}
  CLUSTER_ID: cat210j0nqe29qff0mu7
  CLUSTER_ZONE: ru-central1-d
  CLUSTER_NAME: sandbox


jobs:
  # Сборка и пуш образов в докерхаб:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ env.DOCKER_USER }}
            password: ${{ env.DOCKER_PASSWORD }}

        - name: Push Backend Sandbox to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./deploy/Dockerfile
            push: true
            tags: arturdzh/sandbox:latest

        - name: Push Sandbox for python to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./docker/python/
            push: true
            tags: arturdzh/sandbox-for-python:latest


  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub

      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Install Yandex CLI
          run: |
            curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
            echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

        - name: Auth to Yandex Cloud
          run: |
            echo '$YC_SA_KEY_JSON > key.json
            yc config set service-account-key key.json
            CLOUD_ID=$(jq -r .cloud_id key.json)
            FOLDER_ID=$(jq -r .folder_id key.json)

            yc config set cloud-id $CLOUD_ID
            yc config set folder-id $FOLDER_ID
            yc config set compute-default-zone $CLUSTER_ZONE

        # Добавляем kubeconfig (секретом)    
        - name: Generate kubeconfig
          run: |
            yc managed-kubernetes cluster get-credentials $CLUSTER_ID --external --force
            kubectl config set-context --current --namespace=$SANDBOX_NAMESPACE
            cat ~/.kube/config

        - name: Install Helm
          uses: azure/setup-helm@v4

        # Проверим, что можем подключиться
        - name: Test kubectl connection
          run: |
            kubectl get pods,deployments,services -n $SANDBOX_NAMESPACE

        # Деплой чарта в Kubernetes
        - name: Deploy Helm chart
          env:
            RELEASE_NAME: sandbox
            CHART_NAME: ./sandbox-chart
          run: |
            helm upgrade --install $RELEASE_NAME $CHART_NAME \
              --namespace $SANDBOX_NAMESPACE
